spring:
  application:
    name: user-service

  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/userdb}
    username: ${R2DBC_USERNAME:postgres}
    password: ${R2DBC_PASSWORD:postgres}

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/userdb}

redis:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:changeitpleasechangemeplease32chars}
  expiration-ms: ${JWT_EXP_MS:3600000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
